const express = require('express')
const cookieParser = require('cookie-parser')
const cors = require('cors')
const app = express()

const bagRouter = require('./router/bagRouter')
const registerRouter = require('./router/registerRouter')
const loginRouter = require('./router/loginRouter')
const cartRouter = require('./router/cartRouter')
const productCartRouter = require('./router/productCartRouter')

app.use(cors({ origin: 'http://localhost:3000', credentials: true }))
app.use(cookieParser())
app.use(express.json())
app.use('/login', loginRouter)
app.use('/register', registerRouter)
app.use('/bag', bagRouter)
app.use('/cart', cartRouter)
app.use('/product_cart', productCartRouter)
app.listen(8080, () => {
    console.log('CONNECTED TO BACKEND')
})
